### PR TITLE
CROWD-MONITORING

### PR DESCRIPTION
**Pull request by MEHAK-BENIWAL**
These are my file for crowd monitoring for MehaK Beniwal and Mihir Khatana which inclncludes all our code

### CODE REVIEW

**Comment by ben-AI-cybersec** [comment]
@doubleedesign could you please review this?

**Review by doubleedesign — CHANGES_REQUESTED** [review]
Thanks for your PR! This is a good start in terms of design and content, but it needs to be properly integrated into the React app to be merged.

**Review by doubleedesign — CHANGES_REQUESTED** [review]
Please integrate your code with the existing React app in this repository, rather than adding a new one.

**Comment by doubleedesign** [comment]
I can see a lot of the build errors are related to whitespace, which is easy to fix by setting up your IDE to auto-format on save using the project's ESLint configuration. See [this doc](https://redback-operations.github.io/redback-documentation/docs/web-mobile-app-dev/frontend/submitting-work) for more information 🙂

**Comment by ben-AI-cybersec** [comment]
Issues were never addressed. Closing PR

**Pull request closed without merging**
