### PR TITLE
crowd monitoring

### PR DESCRIPTION
**Pull request by nichokt**

### CODE REVIEW

**Comment by kcf-jackson** [comment]
@nichokt Please remove the `node_modules` folder straightaway. I will start reviewing the pull request after you make the change.

**Comment by kcf-jackson** [comment]
Thanks for the work @nichokt 

The update looks fine to me. This PR continues from #16 and improves the visualisation. Please include a screenshot / gif of the enhanced frontend in the README.md. After the update, please tag `@doubleedesign` for merging.

**Comment by nichokt** [comment]
@doubleedesign Can you please review for merging. Thank you

**Comment by ben-AI-cybersec** [comment]
Hardcoded credentials in line 9 of database.py. @nichokt please rotate credentials IMMEDIATELY, and remove them to a non-uploaded .env

**Pull request closed without merging**
